name: Build images and deploy

on:
  push:
    tags:
      - "v*" # Triggers only on version tags like v1.2.3
  workflow_dispatch: # Manual trigger
    inputs:
      tag_suffix:
        description: 'Tag suffix (e.g., "dev", "qa")'
        required: false
        default: "manual"
      environment:
        description: "Target environment"
        required: true
        default: "production"
        type: choice
        options:
          - production

env:
  AWS_REGION: ap_southeast-2 # set this to your preferred AWS region, e.g. us-west-1
  ECS_SERVICE: onlyone # set this to your Amazon ECS service name
  ECS_CLUSTER: onlyone-service-2d70yetx # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: .aws/onlyone-task-definition.json
  CONTAINER_NAME: bevdev1/onlyone-gameserver:${{ github.ref_name }}

  GAMESERVER_IMAGE: bevdev1/onlyone-gameserver:${{ github.ref_name }}
  NGINX_IMAGE: bevdev1/onlyone-nginx:${{ github.ref_name }}
jobs:
  build-frontend-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build combined nginx+frontend image
      - name: Build and push nginx image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./nginx/Dockerfile
          push: true
          tags: |
            ${{ env.NGINX_IMAGE }}

  build-gameserver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push gameserver image
        uses: docker/build-push-action@v5
        with:
          context: ./gameserver
          file: ./gameserver/Dockerfile
          push: true
          tags: |
            ${{ env.GAMESERVER_IMAGE }}
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ECS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ECS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Fill in the Nginx image id in the Amazon ECS task definition
        id: render-nginx-container
        uses: aws-actions/amazon-ecs-render-task-definition@c804dfbdd57f713b6c079302a4c01db7017a36fc
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: nginx
          image: ${{ env.NGINX_IMAGE }}

      - name: Fill in the Gameserver image id in the Amazon ECS task definition
        id: render-gameserver-container
        uses: aws-actions/amazon-ecs-render-task-definition@c804dfbdd57f713b6c079302a4c01db7017a36fc
        with:
          task-definition: ${{ steps.render-nginx-container.outputs.task-definition }}
          container-name: gameserver
          image: ${{ env.GAMESERVER_IMAGE }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@df9643053eda01f169e64a0e60233aacca83799a
        with:
          task-definition: ${{ steps.render-gameserver-container.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
